### ISSUE TITLE
Download fails with default options when some photos have no title

### ISSUE THREAD

**Issue by w00kie** [beaufour/flickr-download#11]
The default naming setting will give `.jpg` filename to all photos without a title. It really should detect that the title is empty and pick the id instead so that at least we download something.

That or switch to a different default option.

**Comment by beaufour** [comment]
Makes total sense. Fixed in v0.2.8

**Comment by w00kie** [comment]
The default naming method now uses the id if there is no title. However, since I have a lot of untitled photos or sets with the same title on many pics, I use the `title_increment` method and this one did not inherit the new feature so I end up with `.jpg`, `(1).jpg`, `(2).jpg` etc. which is not great.

**Comment by beaufour** [comment]
Try v0.2.9
