### ISSUE TITLE
UnicodeEncodeError when downloading files with unicode characters in their description on Windows 8.1

### ISSUE THREAD

**Issue by EraYaN** [beaufour/flickr-download#12]
Downloading the following album ID: 72157661696317310
(using flickr_download.exe -t -k <key> -s <secret> -d %id%)
gives the following output:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\flickr_download-script.py", line 9, in <module>
    load_entry_point('flickr-download==0.2.12', 'console_scripts', 'flickr_download')()
  File "C:\Python27\lib\site-packages\flickr_download\flick_download.py", line 220, in main
    download_set(args.download, get_filename, args.quality)
  File "C:\Python27\lib\site-packages\flickr_download\flick_download.py", line 121, in download_set
    print('Saving: {0}'.format(fname))
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 50-51: character maps to <undefined>
```

It is probably due to this text: 複製 (it's in the description of https://www.flickr.com/photos/138222944@N04/23047089214/in/album-72157661696317310/) 

I wonder if that is fixable on Windows as there are no real utf8 locales.

**Comment by beaufour** [comment]
@EraYaN Hmm, my knowledge of Windows peaked back at at Windows 95 :smile: ... You are saying you cannot have utf-8 filenames in Windows?

I can strip any non-ascii chars, but that seems terrible...

**Comment by EraYaN** [comment]
You can have utf-8 filenames. The issue lies with how python handles unicode. In this case it's not even the filename but some of the metadata. I think if you do not specify a character set it will default to some cp-5xxx number on windows, if you happen to be in Europe/US. On *nix this is fixable by using one of the *.utf-8 locales, this way python will default to utf-8 internal encoding.

So I think you need to tell python to use utf-8 for everything. So not "charmap" encoding, but "utf-8".

Seems to be something like:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```
Source: https://www.python.org/dev/peps/pep-0263/

And string literals in python 2 need a litlle 'u' prefix.

Other tid-bit: http://stackoverflow.com/questions/10376923/reading-non-ascii-characters-from-a-text-file

Sadly I know very little python, so I can't really be of more help.

I know youtube-dl (video ripper) has a specific switch that can be used to just strip out all non ascii characters (from the filename though not the metadata). (useful for using ffmpeg)

**Comment by beaufour** [comment]
@EraYaN I've been traveling a fair a bit and haven't had a chance to look at this before now, sorry for the delay. I obviously didn't look properly on the stack trace before now, oops. The issue is that you can't, as far as I can see, print unicode to the console in Windows. So I guess I have to prune that from the output printed... I'll have a look

**Comment by beaufour** [comment]
@EraYaN I tried fixing this in 9da3f07f22a29a7cbe36b1425558a9eb4523d45e. Could you try it out?

**Comment by EraYaN** [comment]
It worked, it shows up as ?? in console. The file itself has the correct name.

**Comment by beaufour** [comment]
Super! Thanks for verifying @EraYaN
