### ISSUE TITLE
Cannot download photos that are not in a set

### ISSUE THREAD

**Issue by Flimm** [beaufour/flickr-download#15]
Flickr allows you to not put a photo in a set. I think this is a recent change within the last year, which may explain why this script is not designed for this use-case. It only seems able to download all photos within a set, but not all photos not in a set.

I think the `-u USERNAME` option should be changed to download all photos for a given user, including photos not in a set.

**Comment by beaufour** [comment]
Hmm, odd that I've never actually tested that :-) I agree that the tool should definitely do that.

**Comment by beaufour** [comment]
It has obviously been a while since I thought about that functionality, the help clearly says that `-u` downloads all the sets for a given user :-)

**Comment by beaufour** [comment]
I added support in v0.2.14, use `-p <username>`.
