### ISSUE TITLE
flickr_download not run from crontab

### ISSUE THREAD

**Issue by jknorpp** [beaufour/flickr-download#16]
Hi Allan,

I have your flickr_download successfully running on a Raspberry Pi (os: latest Raspbian).
Running commands from the command line does the job.

I put the command into a flickr_download.sh, made it executable and it is doing it's job like that, too.

Unfortunately my attempt of having cron daemon running the script putting my flickr_download.sh into my user's (or root's) crontab does not execute and outputs following error:

```
File "/usr/local/bin/flickr_download", line 9, in <module>
    load_entry_point('flickr-download==0.2.14', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 252, in main
    if sys.stdout.encoding.lower() != 'utf-8':
AttributeError: 'NoneType' object has no attribute 'lower'
```

I assumed crontab was not using the correct locale settings. Therefore I made sure that crontab is using the same locale like the system. Checking both gives a result as follows:

```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

So for now I don't know where or what for to keep on searching.
I'd be super happy if you had a hint for me where I could continue to finally find a solution.

Thanks a lot in advance and best regards from France
Johannes

**Comment by beaufour** [comment]
Hah, nice that it's running on a Raspberry Pi!

That line was added to get the script running on Windows... Running inside cron is apparently another odd environment. If you add this line in the script that you use to run it, before flickr_download, it could fix it:

```sh
PYTHONIOENCODING=utf8
```

Let me know if that fixes it.

But really I should do it properly in the script somehow.

**Comment by jknorpp** [comment]
Hello again and thanks for the quick response!

Unfortunately it's still not running.

I added to my script as follows:

```
#!/bin/bash

PYTHONIOENCODING=utf8
flickr_download -k 134a0##########32b4b6 -s 676##########379 -d 421###########165 -t
```

Crontab entry is like this

`* * * * * sudo /home/pi/slideshow/flickr_download.sh /home/pi/crontab_flickr_download.log 2>&1`

Do you happen to have another idea?

**Comment by beaufour** [comment]
@jknorpp can you try to the code on the `cron_issues` branch I just added?

https://github.com/beaufour/flickr-download/tree/cron_issues

**Comment by jknorpp** [comment]
@beaufor Will be very happy to try. Might take some days though to find the time. I will report results. Thanks a lot!

--
Johannes Kalt

**Comment by lazzarello** [comment]
It's not cron, it's how the code interacts with UNIX standard output. For example, the following pipeline which should send a list of set ids into the `sets` variable will produce the same error, making the following for loop impossible

```bash
sets=`flickr_download -k ${key} -s ${secret} -l ${username} | awk '{print $1}' | xargs`

for set in ${sets}
do
  flickr_download -k ${key} -s ${secret} -d ${set}
done
```

For clarity, I get the following error output

```
Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 9, in <module>
    load_entry_point('flickr-download==0.2.15', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 252, in main
    if sys.stdout.encoding.lower() != 'utf-8':
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by beaufour** [comment]
@lazzarello yeah, I found out too :) It should be fixed on the `cron_issues` branch. Did you give that a spin?

**Comment by beaufour** [comment]
I'm quite convinced that this is fixed on master. Let me know if it isn't

**Comment by jknorpp** [comment]
Sorry for not getting back to you on this so far. I'm still away and not able to access my Raspberry Pi. Therefore I didn't do any further tests. Will do so maybe end of this week and let you know if it solves my problem. Thanks a lot so far for taking care about it!

**Comment by beaufour** [comment]
@jknorpp no sweat

**Comment by jknorpp** [comment]
@beaufour I upgraded to 0.2.15, ran my cron job and it's working like a charme! :-)
I'm overflowing with gratitude (and so are my parents who now can see up to date pictures of their grandchild in a nice wooden frame on their dining room wall)!
Thank you very much!

**Comment by beaufour** [comment]
@jknorpp no problem! Happy it works. Great use of the utility!
