### ISSUE TITLE
UTF-8 filename and length validation

### ISSUE THREAD

**Issue by lazzarello** [beaufour/flickr-download#17]
I have some photos that I cross-posted from Instagram. It used the description from the source end as the title on the destination end. This produced some humorous results when using the `-p USERNAME` mode with default naming. 

I'll take a look at the code tonight. I imagine this utility will have some growing popularity due to people leaving Flickr after the Verizon Yahoo! purchase. That's how I found it.

```
Saving: lazzarello/new dangly earring. copper and crystal for the Lost Boys look circa 1984. courtesy Lavender Buttons @lavenderbuttons 💋👏.jpg
Saving: lazzarello/Today marks the day I realized I can fit my whole office into a canvas saddle bag attached to the back of my bike. This includes a 15" MacBook Pro, a Happy Hacker Keyboard pro, a Wacom Bamboo tablet and a plastic stand for the computer. I look ridiculous..jpg
Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 9, in <module>
    load_entry_point('flickr-download==0.2.15', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 267, in main
    download_user_photos(args.download_user_photos, get_filename, args.quality)
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 178, in download_user_photos
    download_list(user, username, get_filename, size_label)
  File "/usr/local/lib/python2.7/site-packages/flickr_download-0.2.15-py2.7.egg/flickr_download/flick_download.py", line 146, in download_list
    photo.save(fname, photo_size_label)
  File "/usr/local/lib/python2.7/site-packages/flickr_api/objects.py", line 1313, in save
    with open(filename, 'wb') as f:
IOError: [Errno 63] File name too long: u'lazzarello/Today marks the day I realized I can fit my whole office into a canvas saddle bag attached to the back of my bike. This includes a 15" MacBook Pro, a Happy Hacker Keyboard pro, a Wacom Bamboo tablet and a plastic stand for the computer. I look ridiculous..jpg'
```

**Comment by beaufour** [comment]
You don't normally use emoticons in your filenames? 😄 

I suspect that you are right about the growing popularity.

The error is about a too long filename though... we could truncate it or suggest another naming mode or ?

**Comment by beaufour** [comment]
I made the script continue on IO Errors... not a fantastic solution, but truncating the filename leads to all kinds of edge cases with duplicate names, and I didn't have the time to think it properly through.

**Comment by lazzarello** [comment]
Had a busy weekend. I'll pull the master branch and check it out. Thanks!

**Comment by lazzarello** [comment]
Looks like it's working! Got past the original bad filename. Thanks.

**Comment by beaufour** [comment]
@lazzarello Yay. Thanks for resting. But do note that it just skips that file. No magic to try to shorten the filename :-(
