### ISSUE TITLE
Manage or list previously downloaded images.

### ISSUE THREAD

**Issue by thyme676** [beaufour/flickr-download#23]
It would be very handy to have an option to delete local images that are no longer in the stream. Even if you could just list the images in an album would be very handy.

**Comment by beaufour** [comment]
Just so I understand you right: You would ideally like to be able to "synchronize" whatever is in a Flickr album/stream to a local directory, including deleting files that are no longer in the album/stream?

Alternatively, you would like to be able to just list the file names of a stream/album?

**Comment by thyme676** [comment]
Yes either one would work. Also I have to say this script is so slick!

**Comment by beaufour** [comment]
I have added an `-o` option to v0.2.18 that skips the downloading of the photos, which in effect then just lists the photos.

I've filed #25 to add the delete capability one day. No promises :)
