### ISSUE TITLE
All files are saved as .jpg

### ISSUE THREAD

**Issue by thyme676** [beaufour/flickr-download#24]
On version 2.17 all our files are saved as .jpg. Is there some flag that fixes this, and appends the correct filetype?

**Comment by beaufour** [comment]
To my knowledge Flickr converts all images to JPEGs, so even if you uploaded them as something else you'll still get them back as JPEGs. Unless you are downloading the originals. But if that is what you are doing, you are right then the script just stupidly appends `.jpg` to them too. I'll look at fixing that. But do note that it's only for the originals.

**Comment by thyme676** [comment]
Thanks for the quick response! The file command shows the images downloaded by flickr-download are still the original file-type. I ran into an interesting issue where my image viewer would display some pngs (that were renamed to .jpg) but not others.

**Comment by beaufour** [comment]
This has been fixed in v0.2.18
