### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by darkdragon-001** [beaufour/flickr-download#31]
I get a _User not found_ error for user [151745458@N02](https://www.flickr.com/people/151745458@N02/) when running via `flickr_download -k <api key> -s <api secret> -l 151745458@N02` (of course I inserted my key and secret). I also authorized a token because the photos are not public but accessible with my account.

**Comment by beaufour** [comment]
Sorry for the delay in responding to this, I somehow missed it at first :(

Do you have a profile name too for your account? I.e. I download my own photos using `beaufour` not the Flickr ID. Try using that?

**Comment by darkdragon-001** [comment]
Click on the link to see the public profile page. So this user actually exists and it is the correct ID.
Or what do you mean by _profile name_?

**Comment by darkdragon-001** [comment]
Indeed it is the name. I was thinking something similar with the special characters as well. How do I find out?

**Comment by beaufour** [comment]
I think it's a question about `id` vs `username`. Can you try `-l esn3` ?

**Comment by darkdragon-001** [comment]
You are right, here the `username` is required which is in this case `esn3`. If anyone else is bumping into the same problem, just go to the user page and see the `username` written underneath the display name.

I tried the API [directly](https://www.flickr.com/services/api/explore/flickr.photosets.getInfo) _(here the `id` is needed!)_ and noticed that it only works for public albums (not even my own private ones work -> it always returns _Error 1: Photoset not found_).
