### ISSUE TITLE
Bug: Files skipped if name already exists

### ISSUE THREAD

**Issue by FatKiwi** [beaufour/flickr-download#32]
I've seen albums where each photo is named the same. When downloading It says file exists and skips it.
Can you add something like (1) if file name exists already?
Edit: Oh, looks like #26 is similar.

**Comment by beaufour** [comment]
I'll be the first to admit that the docs aren't stellar :) But if you run `flickr_download -m` you can see the different "naming modes". So if you do `flickr_download -n title_increment` + the rest of your parameters, it should do what you ask for

**Comment by FatKiwi** [comment]
Thanks very much, very helpful!
Updated documentation is going to help many users in future.
