### ISSUE TITLE
Q. iter() returned non-iterator of type 'java.util.ArrayList$Itr'

### ISSUE THREAD

**Issue by hiruoo** [beaufour/flickr-download#38]
![2018-10-25 10 58 39](https://user-images.githubusercontent.com/44471460/47505676-9115d580-d8a9-11e8-915c-71366e064086.png)

iter() returned non-iterator of type 'java.util.ArrayList$Itr'

오류가 뜨는데 어떻게 해결할 수 있나요?ㅠㅠ

**Comment by beaufour** [comment]
It looks like you raised this issue for the wrong project. I think you are looking for this: https://github.com/konlpy/konlpy
