### ISSUE TITLE
iter() returned non-iterator of type 'java.util.ArrayList$Itr'

### ISSUE THREAD

**Issue by hiruoo** [beaufour/flickr-download#39]
![2018-10-26 11 52 54](https://user-images.githubusercontent.com/44471460/47541823-b4766a00-d915-11e8-9bc4-e76e87c141e4.png)

iter() returned non-iterator of type 'java.util.ArrayList$Itr'

**Comment by beaufour** [comment]
It looks like you again raised an issue for the wrong project? I think you are looking for this: https://github.com/konlpy/konlpy
