### ISSUE TITLE
Some photos are lost when there're duplicate names in a photoset

### ISSUE THREAD

**Issue by astanin** [beaufour/flickr-download#46]
If there're two photos in the same set which have the same description "Foo", the script will try to save them both as "Foo.jpg", and only one of them will be saved to disk.

The script should probably save them as "Foo (1).jpg" and "Foo (2).jpg".

**Comment by skyway22** [comment]
switching to a different naming mode, wouldn't re-download all photos again ? so you might end up with doubling some of photos.

**Comment by beaufour** [comment]
It would indeed re-download them, so you would end up with duplicating photos. You have to pick the naming mode before starting the download. I would make the `title_increment` the default naming mode... would probably make sense

**Comment by astanin** [comment]
Probably `title_and_id` is the best default and the easiest to implement. It solves the uniquness problem, and preserves custom names in some form.

An even better solution would be to fetch all photo names before downloading any, and then create a mapping `id` -> unique name (with title increments), and then use names from this map. These names will coincide with the titles most of the time.

**Comment by beaufour** [comment]
After thinking about it for more than a few seconds this time `title_increment` is actually what we want. No need to download all names beforehand, it does exactly what you want. I have changed it in https://github.com/beaufour/flickr-download/pull/49
