### ISSUE TITLE
Run command, return 72157662608843826 - Auto Upload

### ISSUE THREAD

**Issue by funnyEagle** [beaufour/flickr-download#55]
Hi,
I run the command to start the download, but it only returned "72157662608843826 - Auto Upload"
Nothing happened.

what's wrong here?

Thank you!

**Comment by beaufour** [comment]
looks like you ran the `-l` command which lists all the albums. If you want to download that album run the command with `-d 72157662608843826`?

**Comment by funnyEagle** [comment]
Thanks
