### ISSUE TITLE
Error, name too long

### ISSUE THREAD

**Issue by Cholaloula** [beaufour/flickr-download#56]
I wish to download an album from flickr but...

OSError: [Errno 36] File name too long: "Monographie des melastomac\xc3\xa9es, comprenant toutes les plantes de cet ordre r\xc3\xa9cueillies jusqu'\xc3\xa0 ce jour, et notamment au M\xc3\xa8xique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc\xc3\xa8lone, aux Andes de la Nouvelle-Grenade, de Quito et du"

Original album link : 

https://www.flickr.com/photos/biodivlibrary/albums/72157711550179608

Thanks

**Comment by Cholaloula** [comment]
Having the possibility to download the sets renamings download folders with the set ID would work if possible? As I see the naming convention is just for files

**Comment by beaufour** [comment]
That is one long album name :) I have fixed it on master here, but to do a new release I have to clean up a few things since I've fallen behind on Python versions :(

**Comment by Cholaloula** [comment]
Wonderful!!! Thank you very (very very) much!!! You clearly have the most efficient script for Flickr management! : )))

**Comment by Cholaloula** [comment]
Sadly I tried this master branch and even if now the directory name is truncated and doesn't make an error now I have I/O errors writing the files... I'm no coder, just tinkering with the program but maybe the writing part doesn't take in charge the shortened directory name? Usual sets works always like a charm : )

See example : 

Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979173483.jpg (https://www.flickr.com/photos/biodivlibrary/48979173483/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979173138.jpg (https://www.flickr.com/photos/biodivlibrary/48979173138/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979731386.jpg (https://www.flickr.com/photos/biodivlibrary/48979731386/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979909417.jpg (https://www.flickr.com/photos/biodivlibrary/48979909417/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979730776.jpg (https://www.flickr.com/photos/biodivlibrary/48979730776/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979908757.jpg (https://www.flickr.com/photos/biodivlibrary/48979908757/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979730331.jpg (https://www.flickr.com/photos/biodivlibrary/48979730331/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979171333.jpg (https://www.flickr.com/photos/biodivlibrary/48979171333/)
WARNING:root:IO error saving photo: No such file or directory
Saving: Monographie des melastomacées, comprenant toutes les plantes de cet ordre récueillies jusqu'à ce jour, et notamment au Mèxique, dans l'Ile de Cuba, dans les provinces de Caracas, de Cumana, et de Barc/48979907837.jpg (https://www.flickr.com/photos/biodivlibrary/48979907837/)
WARNING:root:IO error saving photo: No such file or directory

Sytem is Debian and python 2.7.16

Thanks : )))

**Comment by beaufour** [comment]
Odd :( The directory name is passed on to the download function correctly.

Does it actually download any of the files. I mean, despite the error are there any files in the directory?

**Comment by Cholaloula** [comment]
Sadly not a single one : ( , did you try on this actual set?

**Comment by beaufour** [comment]
I did, and it worked like a charm. But I messed up my commit it seems :( I updated on master. Can you try again, please?

**Comment by Cholaloula** [comment]
Wonderful! It's perfect! You can't know how thanful I am! It works perfectly : )))

**Comment by beaufour** [comment]
Yay! I'm happy it worked! And no problem.

Sorry about the first miss.... complete stupidity on my end.
