### ISSUE TITLE
Cannot run on Windows (install error?)

### ISSUE THREAD

**Issue by Masterjacker17** [beaufour/flickr-download#61]
Hi there I am very new to computer languages and just got into learning Java. But this project looks interesting and definitely want to try this out. I have installed Python and ran the command pip install flickr_download from cmd and it says successful. Then Where do I set api_key to my api key and secret. I opened flickr_download.py, there in the def init where shall I put my key and secret?. Please help.

**Comment by beaufour** [comment]
Hi there. There are instructions for how to use the API key in the readme tile on the page: https://github.com/beaufour/flickr-download

**Comment by Masterjacker17** [comment]
I tried following the instruction but it is showing me these errors.
![Usssntitled](https://user-images.githubusercontent.com/72133548/94776811-07011080-03e0-11eb-8ceb-dfb9e950a6fd.jpg)

**Comment by beaufour** [comment]
It doesn't look like it even gets to the code. It's failing to start the program which doesn't have anything to do with the API keys. I haven't run Windows in ages, so I don't really know what's going on here I'm afraid. Does other pip installed packages work? Does anything interesting come up if you Google the error message?

**Comment by Masterjacker17** [comment]
I have tried to search for the errors online but no luck

**Comment by beaufour** [comment]
I doesn't look like it's specific to this tool. You have to debug your Python / pip setup. I can't help with that, sorry.
