### ISSUE TITLE
NotADirectoryError: [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by eggplantedd** [beaufour/flickr-download#62]
Hi,

So I am no coder, but I managed to figure out how to use the Python 3 build. I had to overcome the "[No such file or directory](https://github.com/beaufour/flickr-download/issues/48)" error by downloading alexis-mignon's [edited objects.py](https://github.com/alexis-mignon/python-flickr-api/commit/26cb0703a9886dd40b95a878529fe34883de0e7a#diff-ba0e49ef4777e30e65c0d48dd6b674d6632d3a286c5552a13907ba0e404862e9) in python-flickr-api, _then_ having to correct the [photo_file undefined](https://github.com/alexis-mignon/python-flickr-api/commit/26cb0703a9886dd40b95a878529fe34883de0e7a#r33726249) error it produced by re-adding `r = urllib.request.urlopen(photo_file)` after line 1349 as recommended, with spaces _not_ tabs. Phew. 

So this started downloading the files no problem

```
Saving: Dealer Ads 0571\Wall St 2 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51145104308/)
Saving: Camera Ads 0571\Beseler 1 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51145112038/)
Saving: Camera Ads 0571\Da-Lite 1 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51145992720/)
Saving: Camera Ads 0571\Exakta 1 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51144886661/)
Saving: Camera Ads 0571\GAF 1 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51145992155/)
Saving: Camera Ads 0571\Gossen 1 sm 2.jpg (https://www.flickr.com/photos/38552878@N02/51144208917/)
```

Upon encountering a folder with a : colon as it's title, it failed to save and gave me `NotADirectoryError: [WinError 267] The directory name is invalid: 'RR: Minolta SRT-101'`.

Am I missing an option/setting, or is this a genuine error? If so, how could this (and all the other errors caused by 'invalid' file name characters in Windows) be dealt with?

**Comment by eggplantedd** [comment]
I don't know how to properly use Github (yet), but the following additions worked for me:

### Near the top

import re

invalidChar = re.compile(r'[^\w\-_\. ]')


### After `dirname = photos_title.replace(os.sep, "_")`

```
    #If uses invalid character. Should be platform agnostic.
    if invalidChar.findall(dirname):
        print('WARNING: Photoset title "' + (dirname) + '" uses forbidden character. Replacing with an underscore.')
        dirname = re.sub(invalidChar, '_', dirname)

```

**Comment by beaufour** [comment]
Meh. I thought I had taken care of the invalid characters for Windows, but maybe that was only for filenames. I'll have a look at this later. Thanks for reporting and trying to fix it!

And yes, I should try to find the time to move this to Python 3 too... long overdue

**Comment by beaufour** [comment]
@eggplantedd I'm impressed by how much you got working and patched here, without being a coder! I just cleaned up the code and make it work on Python 3 (long overdue!), and I've released a new version of this util (and the underlying `python_flickr_api`). I added a path sanitation library a while back, but it never got released. But it is now.

Can you try to install version 3, and see if it fixed the problem for you?

**Comment by beaufour** [comment]
Fixed in current master
