### ISSUE TITLE
mktime error

### ISSUE THREAD

**Issue by johnbreslin** [beaufour/flickr-download#66]
I've been getting the following error - OverflowError: mktime argument out of range.

I think it's for old photos where the album owner has set it to a date/time too far in the past and unix can't change the date/time to it. Commenting out the date/time change worked for me.

**Comment by beaufour** [comment]
Hmm, ok, I can put a guard in for that. Do you have an example photo or
album where I can test it myself?

**Comment by beaufour** [comment]
I found it easily enough. Here's an example: https://www.flickr.com/photos/154663296@N07/albums/72157680924249693

**Comment by beaufour** [comment]
Fixed in master now. Thanks @johnbreslin !
