### ISSUE TITLE
Add exif data to json

### ISSUE THREAD

**Issue by bogdanstoian1988** [beaufour/flickr-download#67]
Add exif data to json?
Some photos after download lose the exif data, but it's present on Flickr. Example: https://www.flickr.com/photos/jfroberts/45787037825/in/dateposted/

What I do is rename the files after download, because I'm interested on camera or lenses samples, so intead of **29226498103.jpg**
I preffer **LEICA SL Typ 601_Summilux-M 1.4 28 ASPH._29226498103.jpg**

I use a dirty one liner bash script to do so:
```
for FILE in /mnt/f/Pictures/FlickrDownloader/John\ F.\ Roberts/*.jpg; do \
	FILENAME=`basename "${FILE}" | grep -oP '.*.(jpeg|jpg|png)'`;
	MODEL=$(exif "${FILE}" | grep '^Model' | grep -oP '\|.*' | sed 's/|//;s// /' | sed 's/[\/()<>:.\\|?*]\+//g');
	LENS=$(exif "${FILE}" | grep '^Lens Model' | grep -oP '\|.*' | sed 's/|//;s// /' | sed 's/\// /' | sed 's/1://' | sed 's/ f / f/' | sed 's/[\/()<>:\\|?*]\+//g');
	FNAME=$MODEL"_"$LENS"_"$FILENAME;
	NEWFILENAME=$(echo $FNAME | sed 's/^[ \t_]*//g' | sed '/^\s*$/d' | sed 's/__/_/g' );
	mv "${FILE}" "/mnt/f/Pictures/FlickrDownloader/John F. Roberts/${NEWFILENAME}";
done
```

**Comment by beaufour** [comment]
Thanks for the suggestion. Can you point me to a publicly accessible image
where I can see the issue?

**Comment by bogdanstoian1988** [comment]
This would be one: https://www.flickr.com/photos/jfroberts/45787037825/in/dateposted/
If you can't see the link, maybe github has removed it to avoid spamming. Let me know and I'll find another way.

**Comment by beaufour** [comment]
Ah, yeah, I think I need to explicitly download the EXIF information. Ok. Good idea!

I'll take a peak at some point. No promised on the ETA :)

**Comment by beaufour** [comment]
I just added support for saving the exif data to the JSON in the latest master code. You can install directly from github to try it out.
