### ISSUE TITLE
For --download_user_photos, why use name instead of username?

### ISSUE THREAD

**Issue by bogdanstoian1988** [beaufour/flickr-download#68]
For example, in order to download all user's photos we have to specify its literal name like this: --download_user_photos "★☆洪爺の銀鹽專賣★☆"
Wouldn't it be better if we could specify the username like this? Example: --download_user_photos "titsanic002"
This could avoid write issues on disk when the name has special characters.

The username is in the link: https://www.flickr.com/photos/titsanic002/

**Comment by beaufour** [comment]
The API for finding users have always been flaky. It's a Flickr issue. The tool supports all three methods of trying to find the user: username, email, and full url. For that user, Flickr returns "User not found"... I couldn't tell you why. If you use the full url, it finds the user fine, like: `flickr_download.py -l https://www.flickr.com/photos/titsanic002/`

You can see the API results yourself here: https://www.flickr.com/services/api/explore/flickr.people.findByUsername
