### ISSUE TITLE
Album downloads are incomplete

### ISSUE THREAD

**Issue by bogdanstoian1988** [beaufour/flickr-download#69]
For exmaple, this album has 25 photos, but it only downloads 4 photos:

https://www.flickr.com/photos/devorobin/albums/72157675497780042
flickr_download -k *** -s *** --download 72157675497780042 --naming title_and_id

Same issue when trying to download albums of a given user:

https://www.flickr.com/photos/devorobin/albums
flickr_download -k *** -s *** --cache api_cache --metadata_store --download_user "Dwayne Martin"

**Comment by beaufour** [comment]
That's because it's labelled as adult content, so you have to be signed in to Flickr to download those photos. Add `--user-auth` as an argument and then it should work.
