### ISSUE TITLE
Issue with downloading sets for a user

### ISSUE THREAD

**Issue by emikelai** [beaufour/flickr-download#72]
Hi beaufour,

First off, thanks for all the support you've provided. I'm the same user that reported the video downloading issues.

I have two Flickr accounts and am now trying to download all the sets for my 2nd Flickr account. I ran what I believe are the same steps as the first one but get stuck at a very initial stage. I have generated a different api token for each account.

1) When I run this command:
flickr_download -k 5286d917cc468371452813a1140a036e -s <my_secret> --download_user alteramike --user_auth --cach  api_cache --metadata_store
I receive this printout:
INFO:root:Caching is enabled
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Scripts\flickr_download.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 536, in main
    download_user(
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 337, in download_user
    user = find_user(username)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_download\flick_download.py", line 318, in find_user
    user = Flickr.Person.findByUserName(userid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\reflection.py", line 294, in static_call
    r = method_call.call_api(method=flickr_method, **method_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python311\Lib\site-packages\flickr_api\method_call.py", line 150, in call_api
    raise FlickrAPIError(resp["code"], resp["message"])
flickr_api.flickrerrors.FlickrAPIError: 98 : Invalid auth token

+++++++++++++
2) the prior command I ran was this:
flickr_download -k 5286d917cc468371452813a1140a036e -s <my_secret> -t                                                                       
ERROR: Nothing to do?

...and then a printout of the help....
+++++++++++++

I figured I needed to run item (2) before item (1) as per the README but decided to take a shot at running item (1) anyway and the error message is as expected. Do you know why item (2) shows an "ERROR: Nothing to do?" message?

I created an api key via the link you provided:
https://www.flickr.com/services/api/misc.api_keys.html
and that's what I have in the -k and -s fields.

Thanks,
Mike

**Comment by beaufour** [comment]
No problem! I'm happy the tool is helping you. I hope all your other download issues were solved?

I think I know what's going wrong here. I never thought about people downloading from two different accounts. Try deleting the `~/.flickr_token` file, and then try the set up process again? I *think* that should be `C:\Users\Mike\.flickr_token` in your case, but I haven't used Windows in a decade or so, so I could be wrong :)

**Comment by emikelai** [comment]
Hi, I've left a message on the https://github.com/beaufour/flickr-download/issues/18 regarding an additional video issue I'm facing.

For this issue, it looks like the ~/.flickr_token removal works! And yes, it was in C:\Users\Mike\.flickr_token

I'll update you on this after a day of downloading if there are any additional issues faced regarding this second account.

Thanks,
Mike

**Comment by beaufour** [comment]
I added a note to `README.md` about this.

**Comment by emikelai** [comment]
@beaufour Thanks a million for your guidance and support; I was able to successfully use your program to download all of my files before the subscription expired. (the Flickr download feature is unreliable).

**Comment by beaufour** [comment]
Glad to be of help @emikelai and thanks for reporting back!
