### ISSUE TITLE
Improve --help output

### ISSUE THREAD

**Issue by zanna-37** [beaufour/flickr-download#73]
Thank you very very much for this repo! Saved my day. 😃

Just a quick suggestion. In the `--help` output and as well on the README be sure to add these lines:

```bash
-n NAMING_MODE, --naming NAMING_MODE
                        Photo naming mode
                        Tip: Use "flickr_download --list_naming" to get a list or possible NAMING_MODEs
```

and

```bash
-q SIZE_LABEL, --quality SIZE_LABEL
                        Quality of the picture
                        Tip: Refer to Flickr documentation https://www.flickr.com/services/api/flickr.photos.getSizes.html.
                        Examples are: "Original", "Large", "Small", ...
```

That would have saved me time, so I think users would greatly appreciate.

Thanks again!

**Comment by beaufour** [comment]
I'm happy to hear that the tool could help! Good suggestion on adding the `--list_naming` tip. I'll add that.

The challenge with the sizes are that it depends on the photo which ones are available. What is on that page is just an example. I don't actually know where the official documentation is for the sizes. I've seen many different formats over the years. But I can add the Large, Small, etc examples with some text around it.

**Comment by beaufour** [comment]
Added better strings in master

**Comment by zanna-37** [comment]
Maybe add this link https://www.flickr.com/services/api/flickr.photos.getSizes.html so that user can find out for themselves.

Adding a command that given a photo ID, returns all its sizes would be amazing. But I might be an overkill.


_p.s. remember to update the README as well_

**Comment by beaufour** [comment]
thanks for the reminder!
