### ISSUE TITLE
Choose Original over other formats if there's a choice between the largest size

### ISSUE THREAD

**Issue by zanna-37** [beaufour/flickr-download#74]
I noticed that when not specifying `--quality SIZE_LABEL`, the code tries to get the larger one.
However, I don't think this is the best way because you'll probably end up with a file that is larger than the original (!) and without much or its metadata (EXIF).
A better approach would be to download the Original.

What do you think?

**Comment by beaufour** [comment]
Hmm, I would be surprised if Flickr upscaled your images after upload? The code does indeed pick the largest available photo size. That should be the original one, unless that's not available I would think. I just rely on the underlying flickr API code here if you are interested in seeing the logic:
https://github.com/alexis-mignon/python-flickr-api/blob/132304ccd9fc3012db29fdf0762896402f814500/flickr_api/objects.py#L1254

**Comment by zanna-37** [comment]
I opened this because the photo I got without specifying the size was not the original, and when I specifically queried the original I found out it was just slightly smaller. Sadly, enough to fool the corrent system.

**Comment by beaufour** [comment]
Hmm. Is it a public photo so I can see the behavior myself?

**Comment by zanna-37** [comment]
Sure, I'll send it to you by email. By the way, I was slightly wrong, they are the same size, still the default one is not the Original. You can check that by comparing the EXIFs.

**Comment by zanna-37** [comment]
The code you referenced updates the "largest_size" only if the current photo is larger than the largest-so-far. Since the Original and the 5K-one are both of the same size, the first one of the list wins.
I personally think that the code should prefer the one with the label "Original" and fallback to the largest only when the original cannot be found.

**Comment by beaufour** [comment]
I'll be damned. You are right. We should definitely fix that. I'll try to find some time to fix the API.

**Comment by zanna-37** [comment]
Don't worry, I used the `--quality` flag after noticing the problem, so I'm good. I just wanted to let you know because it can be hard to spot for a new user.
Thanks again for your time and the amazing repo!

**Comment by beaufour** [comment]
I'm very happy you reported this. Thank you! And I'm happy the repo has helped you. I fixed the underlying lib just now, but I need to test a bit more and then release both the lib and this repo

https://github.com/alexis-mignon/python-flickr-api/commit/cbfbd5b584a7ab864ae760700297df60b51f7afe

**Comment by beaufour** [comment]
Thanks for the suggestion here, it is now both released in the API and this tool

https://github.com/beaufour/flickr-download/releases/tag/v0.3.4
