### ISSUE TITLE
API error when saving JSON metadata

### ISSUE THREAD

**Issue by chocmake** [beaufour/flickr-download#75]
When trying to download the JSON info/metadata sibling file with a photo it fails to add anything to the JSON and errors with the following:

```
WARNING:root:Trouble saving photo info: <class 'flickr_api.flickrerrors.FlickrAPIError'>
```

Full command and photo used:

```
$ python3 flickr_download -k <key> -s <secret> -i 52693275262 -n id -j
INFO:root:Will save photo info in .json file with same basename as photo
INFO:root:Saving photo info: ./52693275262.jpg.json
WARNING:root:Trouble saving photo info: <class 'flickr_api.flickrerrors.FlickrAPIError'>
INFO:root:Saving: ./52693275262.jpg (https://www.flickr.com/photos/110898173@N04/52693275262/)
```

Then I tried the OAuth authentication method instead using the `-t` command I was able to successfully authenticate according to the terminal messages but it still didn't output a JSON with anything in it.

> What I entered for the script's OAuth verification prompt was the last value in the flickr URL from the plaintext page that appears after allowing the permission on the flickr site (the value from the part named `oauth_verifier=<value>`). Perhaps this wasn't what was meant to be entered? Could use clarification on this.

```
OAuth token was saved, re-run script to use it.
$ python3 flickr_download -k <key> -s <secret> -i 52693275262 -n id -j -t
INFO:root:Will save photo info in .json file with same basename as photo
INFO:root:Saving photo info: ./52693275262.jpg.json
WARNING:root:Trouble saving photo info: <class 'flickr_api.flickrerrors.FlickrAPIError'>
INFO:root:Saving: ./52693275262.jpg (https://www.flickr.com/photos/110898173@N04/52693275262/)
```

Am I missing something?

Environment:
- Kubuntu
- Latest script version installed via pip (had no prior version of the script installed)

**Comment by beaufour** [comment]
It doesn't look like you are doing anything wrong. I'll have a look to see
what's going on.

**Comment by beaufour** [comment]
Ah, I had forgotten that you aren't allowed to download the EXIF data when you are not the photo owner. If you use the current master of the code (do you know how to?), then it should be fixed. It just emits a warning instead failing completely now.

**Comment by chocmake** [comment]
Thanks!

> If you use the current master of the code (do you know how to?)

Not really. Looks like there's just a single file changed, which I assume I could alternatively just simply swap but not sure where that file is located (I'm only aware of the `/.local/bin` directory).

**Comment by beaufour** [comment]
You can install straight from github:

```sh
$ pip install https://github.com/beaufour/flickr-download/archive/refs/heads/master.zip
```

Let me know if it fixes the problem for you

**Comment by chocmake** [comment]
> Let me know if it fixes the problem for you

Appreciated, works now :+1:

**Comment by beaufour** [comment]
> > Let me know if it fixes the problem for you
> 
> Appreciated; works now 👍

Perfect! Thanks for reporting the bug.
