### ISSUE TITLE
python-dateutil dependency update

### ISSUE THREAD

**Issue by huister1216** [beaufour/flickr-download#76]
python-dateutil had an additional updated release in Apr2021 with 2.8.2. 
A few of my other packages in pip require the newer one.
Can you bump the dependency to allow for greater versions for python-dateutil in pyproject.toml?
from
python-dateutil = "2.8.1"
to
python-dateutil = "^2.8.1" 
?

**Comment by beaufour** [comment]
Of course! No clue why I had locked that to a specific version in the first place... It's fixed on master.

**Comment by beaufour** [comment]
And now also released as 0.3.5.
