### ISSUE TITLE
Request: metadata storage for --download_user option

### ISSUE THREAD

**Issue by tomsalden** [beaufour/flickr-download#79]
Hello,

First of all, thank you very much for developing this tool. It is a saviour when making a backup of my Flickr database.

When running the tool, I found out that the metadata option does not seem to work when downloading all sets of a user. I am using this option now to make a copy of all of my Flickr database. However, because of the errors every now and then, I am automatically restarting the script each time.

Even though the cache option already helps a great deal when checking for already downloaded files, I imagine that it would be even smoother with the metadata storage option.

Therefore, I was wondering if it is possible to implement this option for the user sets as well. Hopefully, this is a possibility!

Thank you in advance for your response!

**Comment by beaufour** [comment]
Thanks for the nice words, and happy to hear that the project is helpful!

Can you share the exact command line you use (without any secrets in it : ) )?

**Comment by tomsalden** [comment]
Of course! The command line I use is:

flickr_download -k <api key> -s <api secret> -t --cache api_cache --metadata_store -u <username>

I have authenticated in Flickr with the same username I am downloading from, so I can access all photos.

During the download, I have been looking for the .metadata.db file, but it does not appear. It is not created in the main folder from where I run the command, but also not in the set folders of each downloaded set. The cache file does get edited and changes size now and then.

**Comment by beaufour** [comment]
I think I just forgot to add support for the `--download_user` option... I just added to master. Do you know how to run the script from the master branch?

**Comment by tomsalden** [comment]
Thank you! That works perfectly!

One more comment: the already downloaded photos will not be added to the metadata since you return the "do_download_photo" function after ["if os.path.exists(fname)"](https://github.com/beaufour/flickr-download/blob/master/flickr_download/flick_download.py#L265). That happens just before you would otherwise add it to the metadata database.
So photos that have been downloaded without metadata will always return from this function. However, maybe this is another topic

However, for completely new downloads, it works flawlessly!

**Comment by beaufour** [comment]
Happy it's working!

On the already downloaded... If only I could remember if there was a reason for why I did it in that order... 😀 I'll try to think about it.

**Comment by beaufour** [comment]
Ok, fixed that edge case of updating the metadata store too.
