### ISSUE TITLE
Travel destination pictures

### ISSUE THREAD

**Issue by Adesoji1** [beaufour/flickr-download#84]
How do i use this library to download speccific images?

**Comment by beaufour** [comment]
You can use ```--download_photo``` to download individual pictures. Does that answer your question?

**Comment by Adesoji1** [comment]
yes @beaufour , how do i use this username? https://www.flickr.com/photos/zeeyolqpictures/albums/with/72177720303630754 . his name is 
Yoann JEZEQUEL

**Comment by beaufour** [comment]
If you look in the URL it looks like their username is actually `zeeyolqpictures`

**Comment by Adesoji1** [comment]
i used that too but it didn't work @beaufour
