### ISSUE TITLE
python flickr_download.py -k YOUR_API_KEY -s YOUR_API_SECRET -d CITY_SET_ID

### ISSUE THREAD

**Issue by Adesoji1** [beaufour/flickr-download#85]
Example for downloading images of a city (pseudo-code):
Identify a user or album that has city photos.
List their photosets.
Choose the set that corresponds to a city.
Download the set.
python flickr_download.py -k YOUR_API_KEY -s YOUR_API_SECRET -d CITY_SET_ID
Notes:
The script does not seem to have a feature to search and download images directly by tags or titles; it works based on users and their photo sets.
You might need to manually identify the users or albums that have the images organized in a way that suits your requirement (e.g., based on cities). can we add this to the library so that we can Choose the set that corresponds to a city.

**Comment by beaufour** [comment]
You can download individual sets using the set id using ```--download SET_ID``` which does what you describe here. The Flickr API doesn't know what a set contains, so it will not be possible to add a functionality for download a set that corresponds to a city.

**Comment by Adesoji1** [comment]
@beaufour Can't we implement it then?

**Comment by beaufour** [comment]
the Flickr API (that this util relies on) does not support that.
